services:
  github-navigator:
    image: ghcr.io/luler/hello_github_share:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # 管理员账号配置（可选，不设置则使用默认值 admin/admin123）
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - GITCARD_BASE_URL=${GITCARD_BASE_URL:-http://localhost:3000}
      - JWT_SECRET=${JWT_SECRET:-vdidDXhbSN}
    volumes:
      # 持久化数据库文件
      - .:/app

